import productFetchResponse from "../utils/productResponse";

const products: productFetchResponse[] = [
  {
    external_id: '0',
    name: 'boAt Airdopes 148 In-Ear Truly Wireless Earbuds with Mic (Bluetooth 5.0, Active Black)',
    description: 'boAt Airdopes 148 In-Ear Truly Wireless Earbuds with Mic (Bluetooth 5.0, Active Black)',
    price: 1299,
    rating: 4.4,
    offer: '71%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1664429797/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/247655_0_ixj0ae.png',
    id: 0,
    quantity: 50,
    filter: "normal_deal"
  },
  {
    external_id: '1',
    name: 'OnePlus Bullets Z2 Neckband with AI Noise Cancellation (IP55 Water Resistant, Upto 30 Hours Playback, Acoustic Red)',
    description: 'OnePlus Bullets Z2 Neckband with AI Noise Cancellation (IP55 Water Resistant, Upto 30 Hours Playback, Acoustic Red)',
    price: 1799,
    rating: 4.8,
    offer: '22%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1664409740/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/257082_0_klwmql.png',
    id: 1,
    quantity: 50,
    filter: "normal_deal"
  },
  {
    external_id: '2',
    name: 'Croma 60W Bluetooth Party Speaker with Mic (Voice Assistant, Black)',
    description: 'Croma 60W Bluetooth Party Speaker with Mic (Voice Assistant, Black)',
    price: 6295,
    rating: 4.5,
    offer: '61%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1673527158/Croma%20Assets/Entertainment/Speakers%20and%20Media%20Players/Images/250738_p6txsk.png',
    id: 2,
    quantity: 50,
    filter: "normal_deal"
  },
  {
    external_id: '3',
    name: 'SONY HT-S20R 400W Bluetooth Soundbar with Remote (Dolby Digital, 5.1 Channel, Black)',
    description: 'SONY HT-S20R 400W Bluetooth Soundbar with Remote (Dolby Digital, 5.1 Channel, Black)',
    price: 17990,
    rating: 4.5,
    offer: '10%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1665442699/Croma%20Assets/Entertainment/Speakers%20and%20Media%20Players/Images/224037_0_idsddw.png',
    id: 3,
    quantity: 50,
    filter: "normal_deal"
  },
  {
    external_id: '4',
    name: 'Croma 1400W Bluetooth Party Speaker (Dynamic Bass Boost with Recording Function, Black)',
    description: 'Croma 1400W Bluetooth Party Speaker (Dynamic Bass Boost with Recording Function, Black)',
    price: 15025,
    rating: 4.2,
    offer: '40%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1665443264/Croma%20Assets/Entertainment/Speakers%20and%20Media%20Players/Images/220804_0_o04sdx.png',
    id: 4,
    quantity: 50,
    filter: "normal_deal"
  },
  {
    external_id: '5',
    name: 'pTron InTunes Classic Neckband with Passive Noise Cancellation (IPX4 Water Resistant, 13mm Drivers, Black|Green)',
    description: 'pTron InTunes Classic Neckband with Passive Noise Cancellation (IPX4 Water Resistant, 13mm Drivers, Black|Green)',
    price: 499,
    rating: 0,
    offer: '74%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1681730234/Croma%20Assets/Entertainment/Headphones%20and%20Earphones/Images/272065_bwy1uo.png',
    id: 5,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '6',
    name: 'boAt Airdopes 408 TWS Earbuds (IPX4 Sweat & Water Resistant, 30 Hours Playback, Dark blue)',
    description: 'boAt Airdopes 408 TWS Earbuds (IPX4 Sweat & Water Resistant, 30 Hours Playback, Dark blue)',
    price: 1099,
    rating: 3.9,
    offer: '82%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1674047710/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/240186_0_q6156f.png',
    id: 6,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '7',
    name: 'JBL Tune 230NC JBLT230NCTWSBLK TWS Earbuds with Active Noise Cancellation (Sweat & Water Resistant, 40 Hours Playback, Black)',
    description: 'JBL Tune 230NC JBLT230NCTWSBLK TWS Earbuds with Active Noise Cancellation (Sweat & Water Resistant, 40 Hours Playback, Black)',
    price: 5499,
    rating: 4.2,
    offer: '31%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1674053945/Croma%20Assets/Communication/Headphones%20and%20Earphones/Images/251503_0_cqq8gj.png',
    id: 7,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '8',
    name: 'Boult Audio X60 TWS Earbuds with Active Noise Cancellation (IPX5 Water Resistant, Zen Quad Mic, Blue)',
    description: 'Boult Audio X60 TWS Earbuds with Active Noise Cancellation (IPX5 Water Resistant, Zen Quad Mic, Blue)',
    price: 1799,
    rating: 0,
    offer: '64%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1680168754/Croma%20Assets/Communication/Wearable%20Devices/Images/271286_ekluqo.png',
    id: 8,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '9',
    name: 'Apple 20W Type C Fast Charger (Adapter Only, Optimal Performance, White)',
    description: 'Apple 20W Type C Fast Charger (Adapter Only, Optimal Performance, White)',
    price: 1539,
    rating: 4.7,
    offer: '19%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675859301/Croma%20Assets/Communication/Chargers%20and%20Batteries/Images/230033_0_onjjbc.png',
    id: 9,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '10',
    name: 'Croma 10000 mAh 10W Fast Charging Power Bank (1 Micro USB Type B, 1 Type C & 2 Type A Ports, Aluminium Casing, LED Charging Indicator, Black)',
    description: 'Croma 10000 mAh 10W Fast Charging Power Bank (1 Micro USB Type B, 1 Type C & 2 Type A Ports, Aluminium Casing, LED Charging Indicator, Black)',
    price: 783,
    rating: 4.4,
    offer: '40%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675241195/Croma%20Assets/Communication/PowerBank/Images/225673_td2dak.png',
    id: 10,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '11',
    name: 'Croma Wireless Keyboard & Mouse Combo (1000 DPI, Plug & Play, Black)',
    description: 'Croma Wireless Keyboard & Mouse Combo (1000 DPI, Plug & Play, Black)',
    price: 1199,
    rating: 4.4,
    offer: '52%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1681409441/Croma%20Assets/Computers%20Peripherals/Computer%20Accessories%20and%20Tablets%20Accessories/Images/220996_0_a7fm9l.png',
    id: 11,
    quantity: 50,
    filter: "weekly_deal"
  },
  {
    external_id: '12',
    name: 'SAMSUNG 10W Wireless Charger for iOS, Android (Intertek & SGS Certified, Qi Compatible, White)',
    description: 'SAMSUNG 10W Wireless Charger for iOS, Android (Intertek & SGS Certified, Qi Compatible, White)',
    price: 734,
    rating: 4.5,
    offer: '80%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675862116/Croma%20Assets/Communication/Chargers%20and%20Batteries/Images/228328_0_v0ucic.png',
    id: 12,
    quantity: 50,
    filter: "festival_deal"
  },
  {
    external_id: '13',
    name: 'Croma Type A to Type C 3.9 Feet (1.2M) Cable (Sync and Charge, Black)',
    description: 'Croma Type A to Type C 3.9 Feet (1.2M) Cable (Sync and Charge, Black)',
    price: 129,
    rating: 4.7,
    offer: '82%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675863546/Croma%20Assets/Computers%20Peripherals/Cables%20and%20Connectors/Images/234704_0_v8pisw.png',
    id: 13,
    quantity: 50,
    filter: "festival_deal"
  },
  {
    external_id: '14',
    name: 'logitech M186 Wireless Optical Mouse (1000 DPI, Smooth Cursor Control, Black)',
    description: 'logitech M186 Wireless Optical Mouse (1000 DPI, Smooth Cursor Control, Black)',
    price: 499,
    rating: 3.9,
    offer: '58%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1681402952/Croma%20Assets/Computers%20Peripherals/Computer%20Accessories%20and%20Tablets%20Accessories/Images/252054_0_gknwwu.png',
    id: 14,
    quantity: 50,
    filter: "festival_deal"
  },
  {
    external_id: '15',
    name: 'Croma 20000 mAh 20W Fast Charging Power Bank (1 Micro USB Type B, 1 Type C & 1 Type A Ports, LED Charging Indicator, Blue)',
    description: 'Croma 20000 mAh 20W Fast Charging Power Bank (1 Micro USB Type B, 1 Type C & 1 Type A Ports, LED Charging Indicator, Blue)',
    price: 1371,
    rating: 3.2,
    offer: '54%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675177052/Croma%20Assets/Communication/PowerBank/Images/253120_0_ejhops.png',
    id: 15,
    quantity: 50,
    filter: "festival_deal"
  },
  {
    external_id: '16',
    name: 'Croma Type C to Type C 3.3 Feet (1M) Cable (Nylon Braided, Grey)',
    description: 'Croma Type C to Type C 3.3 Feet (1M) Cable (Nylon Braided, Grey)',
    price: 179,
    rating: 2.8,
    offer: '70%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675864183/Croma%20Assets/Computers%20Peripherals/Cables%20and%20Connectors/Images/255886_0_ddf2tc.png',
    id: 16,
    quantity: 50,
    filter: "festival_deal"
  },
  {
    external_id: '17',
    name: 'Croma 30W Type C Fast Charger (Adapter Only, Multiple Protection, White)',
    description: 'Croma 30W Type C Fast Charger (Adapter Only, Multiple Protection, White)',
    price: 899,
    rating: 4.7,
    offer: '25%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675862804/Croma%20Assets/Communication/Chargers%20and%20Batteries/Images/251807_0_bvm8ou.png',
    id: 17,
    quantity: 50,
    filter: "festival_deal"
  },
  {
    external_id: '18',
    name: 'Croma Type A to Type C, Micro USB 3.9 Feet (1.2M) 2-in-1 Cable (Sync and Charge, Black)',
    description: 'Croma Type A to Type C, Micro USB 3.9 Feet (1.2M) 2-in-1 Cable (Sync and Charge, Black)',
    price: 149,
    rating: 4.4,
    offer: '81%',
    numberOfRatings: 200,
    img: 'https://media.croma.com/image/upload/v1675863520/Croma%20Assets/Computers%20Peripherals/Cables%20and%20Connectors/Images/234705_0_bzwunw.png',
    id: 18,
    quantity: 50,
    filter: "festival_deal"
  }
]



export default products;